const test=require('node:test');const assert=require('node:assert/strict');
const {extractPromptRequirements,inferMechanism,normalizeBlueprint,normalizeSectionBlocks,assembleProject}=require('../lib/preland-pipeline');
const viewport={width:1200,height:800,background:'#090d18'};
test('pipeline creates required sections and keeps them within viewport',()=>{const blueprint=normalizeBlueprint({sections:[{id:'hero',kind:'header',weight:20},{id:'game',kind:'mechanism',weight:60},{id:'end',kind:'footer',weight:20}]},viewport,'большой преленд с колесом');assert.equal(blueprint.mechanismKind,'wheel');assert.equal(blueprint.sections.at(-1).y+blueprint.sections.at(-1).height,800);assert.ok(blueprint.sections.every(section=>section.height>0))});
test('pipeline canonicalizes duplicated and invented LLM sections',()=>{const blueprint=normalizeBlueprint({sections:[{id:'logo',kind:'content',title:'Логотип'},{id:'hero-x',kind:'header'},{id:'game-x',kind:'mechanism'},{id:'extra',kind:'content'},{id:'end-x',kind:'footer'}]},viewport,'колесо');assert.deepEqual(blueprint.sections.map(section=>section.kind),['header','mechanism','content','trust','footer']);assert.deepEqual(blueprint.sections.map(section=>section.id),['hero','game','benefits','trust','final'])});
test('failed section receives deterministic fallback blocks',()=>{const blueprint=normalizeBlueprint({},viewport,'колесо');const section=blueprint.sections.find(item=>item.kind==='mechanism');const blocks=normalizeSectionBlocks(null,section,blueprint,viewport);assert.equal(blocks[0].type,'mechanism');assert.equal(blocks[0].mechanism.kind,'wheel')});
test('pipeline assembles partial LLM results into complete project',()=>{const blueprint=normalizeBlueprint({},viewport,'колесо');const sectionResults={};for(const section of blueprint.sections)sectionResults[section.id]=section.kind==='header'?{blocks:[{id:'custom',type:'text',x:20,y:10,width:400,height:70,content:'Custom',style:{fontSize:40}}]}:null;const project=assembleProject({blueprint,sectionResults,viewport,offerUrl:'https://example.com'});assert.ok(project.blocks.some(block=>block.content==='Custom'));assert.ok(project.blocks.some(block=>block.type==='mechanism'));assert.ok(project.blocks.some(block=>block.type==='button'))});
test('pipeline removes blocks hallucinated into the wrong section',()=>{const blueprint=normalizeBlueprint({},viewport,'колесо');const trust=blueprint.sections.find(section=>section.kind==='trust');const footer=blueprint.sections.find(section=>section.kind==='footer');const trustBlocks=normalizeSectionBlocks({blocks:[{id:'trust-copy',type:'text',x:20,y:trust.y,width:400,height:40,content:'wrong'},{id:'rogue-benefit',type:'text',x:20,y:trust.y+40,width:400,height:40,content:'duplicate'},{id:'rogue-image',type:'image',x:0,y:trust.y,width:1200,height:trust.height,assetPrompt:'wrong background'}]},trust,blueprint,viewport);const footerBlocks=normalizeSectionBlocks({blocks:[{id:'cta-1',type:'button',x:20,y:footer.y,width:400,height:50,content:'wrong'},{id:'cta-2',type:'button',x:20,y:footer.y+50,width:400,height:50,content:'duplicate'}]},footer,blueprint,viewport);assert.equal(trustBlocks.length,1);assert.equal(trustBlocks[0].content,blueprint.socialProof);assert.equal(footerBlocks.length,1);assert.equal(footerBlocks[0].content,blueprint.finalCta)});
test('wheel wording wins over incidental gift wording',()=>{assert.equal(inferMechanism('Механика строго wheel. Крути колесо — твой подарок уже ждёт'),'wheel')});
test('manual mechanic selection is authoritative',()=>{const blueprint=normalizeBlueprint({mechanismKind:'gift_boxes'},viewport,'Сделай колесо удачи','scratch');assert.equal(blueprint.mechanismKind,'scratch')});
test('detailed wheel prompt keeps every mandatory marketing copy item',()=>{const prompt=`Крупный заголовок: «КРУТИ КОЛЕСО И ЗАБЕРИ БОНУС». Подзаголовок: «Испытай удачу — твой подарок уже ждёт».
Колесо с 8 секторами: 50%, 100%, 150%, 200%, 250%, 300%, 400% и 500%.
Карточка акции: «Бонус до 500%», «Доступно 3 попытки», «Подарок активируется после вращения».
Добавь заметную кнопку «КРУТИТЬ КОЛЕСО». После вращения кнопку «ЗАБРАТЬ БОНУС».
Блок преимуществ: «Моментальное начисление», «Без сложных условий», «Доступно новым игрокам».
Социальное доказательство: «Сегодня бонус уже получили 1 284 игрока». В нижней части «ПОЛУЧИТЬ БОНУС».
Графическая модель должна создавать только отдельный фоновый ассет без колеса. Само колесо должно быть настоящим элементом.`;const requirements=extractPromptRequirements(prompt);assert.equal(requirements.headline,'КРУТИ КОЛЕСО И ЗАБЕРИ БОНУС');assert.equal(requirements.subheadline,'Испытай удачу — твой подарок уже ждёт');assert.deepEqual(requirements.prizes,['50%','100%','150%','200%','250%','300%','400%','500%']);assert.deepEqual(requirements.benefits,['Моментальное начисление','Без сложных условий','Доступно новым игрокам']);assert.equal(requirements.socialProof,'Сегодня бонус уже получили 1 284 игрока');assert.equal(requirements.spinCta,'КРУТИТЬ КОЛЕСО');assert.equal(requirements.resultCta,'ЗАБРАТЬ БОНУС');assert.equal(requirements.finalCta,'ПОЛУЧИТЬ БОНУС');assert.equal(requirements.generatedWheelSkin,false);const blueprint=normalizeBlueprint({},viewport,prompt,'wheel');const blocks=blueprint.sections.flatMap(section=>normalizeSectionBlocks({},section,blueprint,viewport));assert.ok(blocks.some(block=>block.content==='КРУТИ КОЛЕСО И ЗАБЕРИ БОНУС'));assert.ok(blocks.some(block=>block.content==='Сегодня бонус уже получили 1 284 игрока'));assert.ok(blocks.some(block=>block.content==='ПОЛУЧИТЬ БОНУС'));assert.equal(blocks.filter(block=>/^Моментальное|^Без сложных|^Доступно новым/.test(block.content)).length,3)});
