const test = require('node:test');
const assert = require('node:assert/strict');
const { sanitizeProject, inferRequestedMechanism, ensureAssetPlan, placeUploadedAsset, renderProject, sanitizePatch, zipProject } = require('../lib/simple-builder');

const demo = {
  name:'Demo',viewport:{width:390,height:844,background:'#090d18'},offerUrl:'https://example.com/offer',
  blocks:[
    {id:'title',type:'text',x:20,y:30,width:350,height:70,content:'Hello',style:{fontSize:40,color:'#ffffff',z:2}},
    {id:'mechanic',type:'mechanism',x:40,y:150,width:310,height:400,style:{background:'#151c2d',z:3},mechanism:{kind:'progressive_reveal',cta:'Open',steps:3,stages:[]}},
    {id:'cta',type:'button',x:50,y:700,width:290,height:60,content:'Continue',style:{background:'#d9ff43',color:'#11120f',z:4}},
  ],
};

test('simple builder compiles movable blocks and protected mechanism runtime',()=>{const output=renderProject(demo);assert.equal(output.validation.ok,true);assert.match(output.html,/progressive_reveal/);assert.match(output.files['core_logic.js'],/cta_click/);assert.match(output.files['core_logic.js'],/click_id/)});
test('simple builder clamps invalid positions and styles',()=>{const dirty=structuredClone(demo);dirty.blocks[0].x=9999;dirty.blocks[0].style.fontSize=999;const clean=sanitizeProject(dirty);assert.ok(clean.blocks[0].x<=390-clean.blocks[0].width);assert.equal(clean.blocks[0].style.fontSize,160)});
test('simple block AI patch cannot inject html',()=>{const original=sanitizeProject(demo).blocks[0];const patch=sanitizePatch({content:'<script>bad</script>',style:{fontSize:55}},original);assert.doesNotMatch(patch.content,/[<>]/);assert.equal(patch.style.fontSize,55)});
test('simple builder exports zip',()=>{const output=zipProject(demo);assert.equal(output.archive.readUInt32LE(0),0x04034b50)});
test('simple builder embeds selected local font in preview and zip',()=>{const styled=structuredClone(demo);styled.blocks[0].style.fontFamily='Russo One';const output=zipProject(styled);assert.match(output.html,/@font-face\{font-family:"Russo One"/);assert.match(output.html,/font-family:'Russo One'/);assert.ok(output.archive.includes(Buffer.from('preland/assets/fonts/russo-one-cyrillic-400-normal.woff2')))});
test('mechanism renderer inserts generated images into gift boxes',()=>{const gift=structuredClone(demo);gift.blocks[1].mechanism={kind:'gift_boxes',cta:'Open',steps:1,stages:[{src:'https://example.com/box1.png'},{src:'https://example.com/box2.png'},{src:'https://example.com/box3.png'}]};gift.blocks[1].src='https://example.com/background.png';const output=renderProject(gift);assert.match(output.html,/box1\.png/);assert.match(output.html,/box2\.png/);assert.match(output.html,/box3\.png/);assert.match(output.html,/background\.png/);assert.match(output.html,/gift-box/)});
test('asset planner creates embeddable background and three transparent gift-box cutouts',()=>{const gift=structuredClone(demo);gift.blocks[1].mechanism={kind:'gift_boxes',cta:'Open',steps:1,stages:[]};const project=ensureAssetPlan(gift,'праздничные золотые коробки');assert.equal(project.blocks[1].assetRole,'background');assert.ok(project.blocks[1].assetPrompt);assert.equal(project.blocks[1].mechanism.stages.length,3);assert.ok(project.blocks[1].mechanism.stages.every(stage=>stage.assetRole==='object'&&/single gift box/.test(stage.assetPrompt)&&/transparent background with alpha channel/.test(stage.assetPrompt)&&/No backdrop/.test(stage.assetPrompt)))});
test('gift-box system prompt overrides a scene requested by the LLM or user',()=>{const gift=structuredClone(demo);gift.blocks[1].mechanism={kind:'gift_boxes',cta:'Open',steps:1,stages:[{assetPrompt:'three boxes in a casino room with a woman and text'},{assetPrompt:'box on a colored floor'},{assetPrompt:'complete banner scene'}]};const project=ensureAssetPlan(gift,'нарисуй коробки в комнате с фоном и надписями');for(const stage of project.blocks.find(block=>block.type==='mechanism').mechanism.stages){assert.doesNotMatch(stage.assetPrompt,/casino room|colored floor|complete banner/);assert.match(stage.assetPrompt,/output must contain only the single gift box/);assert.match(stage.assetPrompt,/transparent background with alpha channel/)}});
test('uploaded image can replace the page background and survives rendering',()=>{const source='/uploads/example.png';const placed=placeUploadedAsset(demo,source,'замени фон страницы');assert.equal(placed.target,'фон страницы');assert.match(renderProject(placed.project).html,/\/uploads\/example\.png/)});
test('asset planner creates requested mechanic even when LLM omitted it',()=>{const withoutMechanic=structuredClone(demo);withoutMechanic.blocks=withoutMechanic.blocks.filter(block=>block.type!=='mechanism');withoutMechanic.blocks.push({id:'decor',type:'shape',x:0,y:0,width:390,height:844,assetPrompt:'Dark festive background with bokeh',style:{z:0}});const project=ensureAssetPlan(withoutMechanic,'преленд с тремя подарочными коробками');const mechanism=project.blocks.find(block=>block.type==='mechanism');assert.equal(mechanism.mechanism.kind,'gift_boxes');assert.equal(mechanism.mechanism.stages.length,3);assert.ok(project.blocks.some(block=>block.type==='image'&&block.assetRole==='background'&&block.assetPrompt))});
test('strict wheel is not replaced by gift wording and uses a clean page background',()=>{assert.equal(inferRequestedMechanism('Механика строго wheel, твой подарок ждёт'),'wheel');const wheel=ensureAssetPlan(demo,'Механика строго wheel, твой подарок ждёт');const mechanism=wheel.blocks.find(block=>block.type==='mechanism');const background=wheel.blocks.find(block=>block.type==='image'&&block.assetRole==='background');assert.equal(mechanism.mechanism.kind,'wheel');assert.equal(mechanism.mechanism.stages.length,0);assert.equal(mechanism.mechanism.prizes.length,8);assert.match(background.assetPrompt,/Abstract premium casino atmosphere/);assert.equal(mechanism.assetPrompt,'')});
test('wheel skin is generated only when explicitly enabled',()=>{const skin=structuredClone(demo);skin.blocks[1].mechanism={kind:'wheel',cta:'Open',generatedWheelSkin:true,stages:[],prizes:[]};const project=ensureAssetPlan(skin,'Механика строго wheel');const mechanism=project.blocks.find(block=>block.type==='mechanism');assert.equal(mechanism.mechanism.stages.length,1);assert.match(mechanism.mechanism.stages[0].assetPrompt,/exactly 8 equal blank sectors/)});
test('wheel skin is embedded inside the rotating wheel',()=>{const wheel=structuredClone(demo);wheel.blocks[1].mechanism={kind:'wheel',cta:'Забрать',steps:1,stages:[{src:'/generated/wheel.jpg'}],prizes:['50%','100%','150%','200%','250%','300%','400%','500%']};const output=renderProject(wheel);assert.match(output.html,/class="wheel-skin" src="\/generated\/wheel\.jpg"/);assert.equal((output.html.match(/class="wheel-label"/g)||[]).length,8)});
test('wheel runtime includes spin button, win state and CTA reveal',()=>{const wheel=structuredClone(demo);wheel.blocks[1].mechanism={kind:'wheel',cta:'ЗАБРАТЬ БОНУС',spinCta:'КРУТИТЬ КОЛЕСО',resultText:'ВЫ ВЫИГРАЛИ',offerLines:['Бонус до 500%','Доступно 3 попытки'],prizes:['50%','100%','150%','200%','250%','300%','400%','500%']};const output=renderProject(wheel);assert.match(output.html,/КРУТИТЬ КОЛЕСО/);assert.match(output.html,/Бонус до 500%/);assert.match(output.files['core_logic.js'],/wheel_spin/);assert.match(output.files['core_logic.js'],/classList\.add\('won'\)/)});
test('scratch renders generated prize and real pointer-driven canvas erasing',()=>{const scratch=structuredClone(demo);scratch.blocks[1].mechanism={kind:'scratch',cta:'ЗАБРАТЬ БОНУС',steps:1,stages:[{src:'/generated/prize.jpg'}]};const output=renderProject(scratch);assert.match(output.html,/class="scratch-prize" src="\/generated\/prize\.jpg"/);assert.match(output.html,/class="scratch-canvas"/);assert.match(output.files['core_logic.js'],/addEventListener\('pointerdown'/);assert.match(output.files['core_logic.js'],/globalCompositeOperation='destination-out'/);assert.match(output.files['core_logic.js'],/percent>=52/);assert.doesNotMatch(output.files['core_logic.js'],/scratch-cover/);assert.doesNotThrow(()=>new Function(output.files['core_logic.js']))});
test('scratch asset planner separates clean page background and prize',()=>{const scratch=structuredClone(demo);scratch.blocks[1].mechanism={kind:'scratch',cta:'Open',steps:1,stages:[{assetPrompt:'draw the whole webpage with text'}]};const project=ensureAssetPlan(scratch,'Механика строго scratch, нарисуй всю страницу картинкой');const mechanism=project.blocks.find(block=>block.type==='mechanism');const background=project.blocks.find(block=>block.type==='image'&&block.assetRole==='background');assert.match(background.assetPrompt,/no scratch card/);assert.equal(mechanism.assetPrompt,'');assert.equal(mechanism.mechanism.stages.length,1);assert.match(mechanism.mechanism.stages[0].assetPrompt,/One premium golden casino prize object/);assert.doesNotMatch(mechanism.mechanism.stages[0].assetPrompt,/whole webpage/)});
