const ARCHIVE_MECHANICS = [
  {id:'adult_blurred_18_gate',category:'Adult content',name:'Размытый фон + проверка 18+',icon:'18+'},
  {id:'adult_progressive_reveal',category:'Adult content',name:'Постепенное открытие изображения',icon:'▦'},
  {id:'adult_fake_player_preview',category:'Adult content',name:'Полноэкранный видеоплеер',icon:'▶'},
  {id:'adult_video_loading',category:'Adult content',name:'Загрузка видео',icon:'◌'},
  {id:'adult_category_selector',category:'Adult content',name:'Выбор категории из 4 изображений',icon:'▦'},
  {id:'adult_premium_unlock',category:'Adult content',name:'Разблокировка Premium',icon:'🔒'},
  {id:'adult_dating_18_gate',category:'Adult dating',name:'Выбор типа знакомства',icon:'♥'},
  {id:'adult_dating_quiz_3step',category:'Adult dating',name:'Dating-квиз из 3 вопросов',icon:'?'},
  {id:'adult_dating_nearby_matches',category:'Adult dating',name:'Анкеты рядом',icon:'⌖'},
  {id:'adult_dating_profile_carousel',category:'Adult dating',name:'Карусель анкет',icon:'↔'},
  {id:'adult_dating_blurred_profiles',category:'Adult dating',name:'Сетка размытых анкет',icon:'▦'},
  {id:'adult_dating_chat_preview',category:'Adult dating',name:'Preview интерфейса чата',icon:'◫'},
  {id:'casino_spin_wheel_win',category:'Casino',name:'Полноэкранное колесо бонусов',icon:'◉'},
  {id:'casino_scratch_bonus',category:'Casino',name:'Стираемая бонусная карта',icon:'▨'},
  {id:'casino_slot_minigame',category:'Casino',name:'Мини-слот',icon:'777'},
  {id:'casino_pick_a_box',category:'Casino',name:'Выбор сундука',icon:'🎁'},
  {id:'casino_lucky_card',category:'Casino',name:'Выбор счастливой карты',icon:'🂠'},
  {id:'casino_toplist_bonus',category:'Casino',name:'Рейтинг казино',icon:'★'},
  {id:'betting_match_prediction',category:'Betting',name:'Прогноз матча',icon:'VS'},
  {id:'betting_free_bet_unlock',category:'Betting',name:'Полноэкранный Free Bet',icon:'FB'},
  {id:'betting_odds_countdown',category:'Betting',name:'Коэффициент с таймером',icon:'⏱'},
  {id:'sweep_mystery_box',category:'Sweepstakes',name:'Таинственная коробка',icon:'?'},
  {id:'sweep_prize_wheel',category:'Sweepstakes',name:'Колесо призов',icon:'◉'},
  {id:'sweep_survey_3q',category:'Sweepstakes',name:'Опрос из 3 вопросов',icon:'☑'},
  {id:'nutra_problem_solution_quiz',category:'Nutra / beauty',name:'Квиз по подбору решения',icon:'✦'},
  {id:'nutra_before_after_story',category:'Nutra / beauty',name:'История «до и после»',icon:'↔'},
  {id:'nutra_discount_timer',category:'Nutra / beauty',name:'Продукт со скидкой и таймером',icon:'%'},
  {id:'finance_loan_calculator',category:'Finance',name:'Калькулятор займа',icon:'₽'},
  {id:'finance_approval_check',category:'Finance',name:'Проверка предложения',icon:'✓'},
  {id:'utility_device_check',category:'Utilities',name:'Проверка устройства',icon:'⚙'},
];

const ARCHIVE_IDS = new Set(ARCHIVE_MECHANICS.map(item=>item.id));

module.exports={ARCHIVE_MECHANICS,ARCHIVE_IDS};
